Progress:   0%|                                                                                              | 0/90 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    init_and_train_model(args.verbose)
  File "main.py", line 106, in init_and_train_model
    DeepSeg.train_model()
  File "/root/research/deep-segmentation/segmentation/segmentation.py", line 253, in train_model
    training_losses, validation_losses, lr_rates = trainer.run_trainer()
  File "/root/research/deep-segmentation/segmentation/trainer.py", line 59, in run_trainer
    self._train()
  File "/root/research/deep-segmentation/segmentation/trainer.py", line 94, in _train
    loss = self.criterion(out, target)  # calculate loss
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/research/deep-segmentation/segmentation/loss.py", line 47, in forward
    BCE = F.binary_cross_entropy(inputs, targets, reduction='mean')
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2893, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: Found dtype Long but expected Float