
######################### Loading and Augmenting Images #########################
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    init_and_train_model(args.verbose)
  File "main.py", line 76, in init_and_train_model
    DeepSeg.initialize_model()
  File "/root/research/deep-segmentation/segmentation/unet/segmentation.py", line 209, in initialize_model
    summary(self.model, (1, 512, 512), device="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/research/deep-segmentation/segmentation/unet/unet.py", line 379, in forward
    x, before_pooling = module(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/root/research/deep-segmentation/segmentation/unet/unet.py", line 183, in forward
    y = self.conv1(x)  # convolution 1
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor