
######################### Loading and Augmenting Images #########################
Progress:   0%|                                                                                                                           | 0/30 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)                                                       | 0/17 [00:00<?, ?it/s]
######################### Start Training #########################
































































Training: (loss 0.5085):  82%|█████████████████████████████████████████████████████████████████████████████████▌                 | 14/17 [00:17<00:03,  1.25s/it]
















































































































































































































































































































































































Validation: (loss 0.3765):  60%|███████████████████████████████████████████████████████████▍                                       | 3/5 [00:05<00:03,  1.79s/it]
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    init_and_train_model(args.verbose)
  File "main.py", line 70, in init_and_train_model
    DeepSeg.load_val_images('unet.pt')
  File "/root/research/deep-segmentation/segmentation/unet/segmentation.py", line 296, in load_val_images
    model_weights = torch.load(pathlib.Path.cwd() / model_name, map_location=device)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/research/deep-segmentation/unet.pt'